#include "codec.h"
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdio.h>

// Boundary symbols automatically generated by the ELF linker
extern const KoniCodecImpl* const __start_koni_codecs[] __attribute__((weak));
extern const KoniCodecImpl* const __stop_koni_codecs[] __attribute__((weak));

void koni_codecs_init(void) {
}

static inline size_t get_codec_count(void) {
    if (!__start_koni_codecs || !__stop_koni_codecs) return 0;
    return (size_t)(__stop_koni_codecs - __start_koni_codecs);
}

const KoniCodecImpl* koni_find_codec_by_ext(const char* filepath) {
    if (!filepath) return NULL;
    const char* ext = strrchr(filepath, '.');
    if (!ext) return NULL;

    size_t count = get_codec_count();
    for (size_t i = 0; i < count; i++) {
        const KoniCodecImpl* codec = __start_koni_codecs[i];
        if (!codec || !codec->supported_extensions) continue;

        for (int j = 0; codec->supported_extensions[j] != NULL; j++) {
            if (strcasecmp(ext, codec->supported_extensions[j]) == 0) {
                return codec;
            }
        }
    }
    return NULL;
}

bool koni_is_supported_extension(const char* ext) {
    if (!ext) return false;

    size_t count = get_codec_count();
    for (size_t i = 0; i < count; i++) {
        const KoniCodecImpl* codec = __start_koni_codecs[i];
        if (!codec || !codec->supported_extensions) continue;

        for (int j = 0; codec->supported_extensions[j] != NULL; j++) {
            if (strcasecmp(ext, codec->supported_extensions[j]) == 0) {
                return true;
            }
        }
    }
    return false;
}

void koni_metadata_free(KoniMetadata* meta) {
    if (!meta) return;
    if (meta->title) free(meta->title);
    if (meta->artist) free(meta->artist);
    if (meta->album) free(meta->album);
    if (meta->lyrics) free(meta->lyrics);
    if (meta->art_url) {
        if (strncmp(meta->art_url, "file://", 7) == 0) {
            remove(meta->art_url + 7);
        }
        free(meta->art_url);
    }
    memset(meta, 0, sizeof(KoniMetadata));
}