#define _DEFAULT_SOURCE
#define _GNU_SOURCE

#include "codec.h"
#include "koni_paths.h"
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdio.h>
#include <dirent.h>
#include <unistd.h>
#include <sys/stat.h>

// Boundary symbols automatically generated by the ELF linker
extern const KoniCodecImpl* const __start_koni_codecs[] __attribute__((weak));
extern const KoniCodecImpl* const __stop_koni_codecs[] __attribute__((weak));

static void get_temp_art_dir(char *out_buf, size_t sz) {
    const char *tmp = getenv("TMPDIR");
    if (!tmp || !tmp[0]) tmp = getenv("HOME");
    if (!tmp || !tmp[0]) tmp = koni_get_base_dir();
    snprintf(out_buf, sz, "%s/koni_art", tmp);
}

void koni_codecs_init(void) {
    char dir[1024];
    get_temp_art_dir(dir, sizeof(dir));

    // Wipe any orphaned temporary cover files from previous sessions
    DIR *d = opendir(dir);
    if (d) {
        struct dirent *ent;
        while ((ent = readdir(d)) != NULL) {
            if (ent->d_name[0] == '.') continue;
            char file_path[1024];
            snprintf(file_path, sizeof(file_path), "%s/%s", dir, ent->d_name);
            unlink(file_path);
        }
        closedir(d);
    } else {
        mkdir(dir, 0755);
    }
}

char* koni_codec_save_temp_art(const uint8_t *data, size_t size, const char *ext_hint) {
    if (!data || size == 0) return NULL;

    char dir[1024];
    get_temp_art_dir(dir, sizeof(dir));
    mkdir(dir, 0755);

    const char *ext = ".jpg";
    if (ext_hint && ext_hint[0]) {
        ext = ext_hint;
    } else if (size >= 4 && data[0] == 0x89 && data[1] == 'P' && data[2] == 'N' && data[3] == 'G') {
        ext = ".png";
    }

    char tmpl[1024];
    snprintf(tmpl, sizeof(tmpl), "%s/cover_XXXXXX", dir);
    int fd = mkstemp(tmpl);
    if (fd < 0) return NULL;

    size_t written = 0;
    while (written < size) {
        ssize_t res = write(fd, data + written, size - written);
        if (res <= 0) break;
        written += (size_t)res;
    }
    close(fd);

    char final_path[1024];
    snprintf(final_path, sizeof(final_path), "%s%s", tmpl, ext);
    if (rename(tmpl, final_path) != 0) {
        unlink(tmpl);
        return NULL;
    }

    char *url = malloc(strlen(final_path) + 8);
    if (url) {
        sprintf(url, "file://%s", final_path);
    }
    return url;
}

extern const KoniCodecImpl ma_codec_impl;
extern const KoniCodecImpl ogg_codec_impl;
extern const KoniCodecImpl pxtone_codec_impl;
extern const KoniCodecImpl opus_codec_impl __attribute__((weak));
extern const KoniCodecImpl m4a_codec_impl __attribute__((weak));
extern const KoniCodecImpl dana_codec_impl __attribute__((weak));

static const KoniCodecImpl* const s_all_codecs[] = {
    &ma_codec_impl,
    &ogg_codec_impl,
    &pxtone_codec_impl,
    &opus_codec_impl,
    &m4a_codec_impl,
    &dana_codec_impl,
    NULL
};

const KoniCodecImpl* koni_find_codec_by_ext(const char* filepath) {
    if (!filepath) return NULL;
    const char* ext = strrchr(filepath, '.');
    if (!ext) return NULL;

    for (int i = 0; s_all_codecs[i] != NULL; i++) {
        const KoniCodecImpl* codec = s_all_codecs[i];
        if (!codec || !codec->supported_extensions) continue;

        for (int j = 0; codec->supported_extensions[j] != NULL; j++) {
            if (strcasecmp(ext, codec->supported_extensions[j]) == 0) {
                return codec;
            }
        }
    }
    return NULL;
}

bool koni_is_supported_extension(const char* ext) {
    if (!ext) return false;

    for (int i = 0; s_all_codecs[i] != NULL; i++) {
        const KoniCodecImpl* codec = s_all_codecs[i];
        if (!codec || !codec->supported_extensions) continue;

        for (int j = 0; codec->supported_extensions[j] != NULL; j++) {
            if (strcasecmp(ext, codec->supported_extensions[j]) == 0) {
                return true;
            }
        }
    }
    return false;
}

void koni_metadata_free(KoniMetadata* meta) {
    if (!meta) return;
    if (meta->title) free(meta->title);
    if (meta->artist) free(meta->artist);
    if (meta->album) free(meta->album);
    if (meta->lyrics) free(meta->lyrics);
    if (meta->art_url) {
        if (strncmp(meta->art_url, "file://", 7) == 0) {
            remove(meta->art_url + 7);
        }
        free(meta->art_url);
    }
    memset(meta, 0, sizeof(KoniMetadata));
}